import { HorizontalBox, VerticalBox, ListView, StandardListView, GroupBox, CheckBox } from "std-widgets.slint";
import { GlobalSettings } from "../global_settings.slint";
import { Page } from "./page.slint";

export component SourceListPage inherits Page {
    title: @tr("ListView");
    description: @tr("ListViews can be used to display a list of elements. The StandardListBox is like the default ListView just with a default text based definition of the visual items. Both can be imported from \"std-widgets.slint\"");

    HorizontalBox {
        vertical-stretch: 1;

        GroupBox {
            title: "StandardListView";
            vertical-stretch: 0;

            // StandardListView {
            //     model: [
            //         {text: @tr("Lorem")}, {text: @tr("ipsum")},{text: @tr("dolor")},{text: @tr("sit")},{text: @tr("amet")},{text: @tr("consetetur")},
            //         {text: @tr("Lorem")}, {text: @tr("ipsum")},{text: @tr("dolor")},{text: @tr("sit")},{text: @tr("amet")},{text: @tr("consetetur")},
            //         {text: @tr("Lorem")}, {text: @tr("ipsum")},{text: @tr("dolor")},{text: @tr("sit")},{text: @tr("amet")},{text: @tr("consetetur")},
            //         {text: @tr("Lorem")}, {text: @tr("ipsum")},{text: @tr("dolor")},{text: @tr("sit")},{text: @tr("amet")},{text: @tr("consetetur")},
            //         {text: @tr("Lorem")}, {text: @tr("ipsum")},{text: @tr("dolor")},{text: @tr("sit")},{text: @tr("amet")},{text: @tr("consetetur")},
            //         {text: @tr("Lorem")}, {text: @tr("ipsum")},{text: @tr("dolor")},{text: @tr("sit")},{text: @tr("amet")},{text: @tr("consetetur")},
            //         {text: @tr("Lorem")}, {text: @tr("ipsum")},{text: @tr("dolor")},{text: @tr("sit")},{text: @tr("amet")},{text: @tr("consetetur")},
            //     ];
            // }

            list-view := ListView {
                padding-right: 24px;

                for item in GlobalSettings.sources: HorizontalLayout {
                    padding-left: 24px;

                    CheckBox {
                        text: item.label;
                        checked: item.checked;
                        toggled => {
                            item.checked = self.checked;
                            GlobalSettings.update-selected-source(item.value, self.checked);
                        }
                    }
                }
        }
        }
    }
}
