import { Button, VerticalBox, CheckBox, Spinner, StandardButton, ComboBox, HorizontalBox, GridBox, ScrollView, GroupBox, ListView } from "std-widgets.slint";

struct UiSource {
    name: string,
    source: string,
    // version: string,
    checked: bool,
}

struct UiRune {
    uuid: string,
    name: string,
    position: string,
    rune_image1: image,
    rune_image2: image,
    rune_image3: image,
}

export component AppWindow inherits Window {
    width: 400px;
    height: 500px;
    title: "ChampR";

    in-out property <[UiSource]> source_list: [];
    in property <bool> lcu_running: false;
    callback apply_builds();

    if root.source_list.length == 0: VerticalBox {
        Spinner {
            max-height: 50px;
            max-width: 50px;
            indeterminate: true;
        }
    }

    if root.source_list.length > 0: VerticalBox {
        for source[i] in root.source_list: CheckBox {
            text: source.name;
            checked: source.checked;
            toggled => {
                source.checked = !source.checked;
            }
        }
        if root.lcu_running: VerticalBox {
            Button {
                height: 30px;
                width: 200px;
                text: "Apply Selected Sources";
                primary: true;
                clicked => {
                    root.apply_builds();
                }
            }
        }
        if !root.lcu_running: VerticalBox {
            Text {
                text: "League is not running, please start it first.";
            }
        }
    }
}

export component RuneWindow inherits Dialog {
    title: "Runes";
    // always-on-top: true;
    width: 600px;
    height: 500px;

    in-out property <string> lcu_auth: "";
    in-out property <int> champion_id: 0;
    in-out property <bool> on_top: false;
    in-out property <[string]> source_list: [];
    in-out property <string> selected_source: "";
    in-out property <int> selected_source_index: 0;
    in-out property <image> champion_icon: @image-url("../../../assets/logo.png");
    in-out property <[UiRune]> rune_list: [];
    in-out property <bool> random_champion_mode: false;

    callback refetch_data(string, int);
    callback random_champion(bool);
    callback apply_rune(int, string);

    changed champion_id => {
        debug("champion_id changed to: ", root.champion_id);
        root.champion_id = root.champion_id;
        root.refetch_data(root.source_list[root.selected_source_index], root.champion_id);
    }
    changed selected_source_index => {
        debug("selected_source_index: changed to", root.selected_source_index);
        root.refetch_data(root.source_list[root.selected_source_index], root.champion_id);
    }

    ScrollView {
        VerticalLayout {
            height: parent.height;

            HorizontalBox {
                Image {
                    height: 30px;
                    width: 30px;
                    source: root.champion_icon;
                }

                ComboBox {
                    width: 200px;
                    height: 30px;
                    model: root.source_list;
                    current-index: root.selected_source_index;
                    changed current-index => {
                        root.selected_source_index = self.current-index;
                        root.selected_source = self.current-value;
                    }
                }

                // Button {
                //     text: "Random Champion Mode: " + (root.random_champion_mode ? "ON" : "OFF");
                //     clicked => {
                //         root.random_champion(root.random_champion_mode);
                //     }
                // }
            }

            GroupBox {
                title: "Runes";

                ListView {
                    for rune[i] in root.rune_list: Rectangle {
                        border-width: 1px;
                        border-color: #F6F6FA;
                        border-radius: 4px;
                        HorizontalBox {
                            height: 100px;
                            alignment: space-around;

                            VerticalBox {
                                Rectangle {
                                    vertical-stretch: 0.0;
                                    Text {
                                        text: rune.name;
                                    }
                                }

                                HorizontalBox {
                                    height: 36px;
                                    vertical-stretch: 0.0;
                                    Image {
                                        horizontal-stretch: 0.0;
                                        height: 24px;
                                        width: 24px;
                                        source: rune.rune_image1;
                                    }

                                    Image {
                                        horizontal-stretch: 0.0;
                                        height: 24px;
                                        width: 24px;
                                        source: rune.rune_image2;
                                    }

                                    Image {
                                        horizontal-stretch: 0.0;
                                        height: 24px;
                                        width: 24px;
                                        source: rune.rune_image3;
                                    }

                                    Rectangle {
                                        vertical-stretch: 1;
                                        Text {
                                            text: rune.position;
                                        }
                                    }
                                }
                            }

                            VerticalBox {
                                height: parent.height;
                                alignment: center;
                                Button {
                                    text: "Apply Rune";
                                    width: 10rem;
                                    clicked => {
                                        root.apply_rune(root.champion_id, rune.uuid);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
