import { Button, VerticalBox, CheckBox } from "std-widgets.slint";

struct UiSource {
    name: string,
    source: string,
    // version: string,
    checked: bool,
}

export component AppWindow inherits Window {
    width: 400px;
    height: 500px;
    title: "ChampR";

    in-out property <[UiSource]> source-list: [];
    callback apply-builds();

    VerticalBox {
        for source[i] in root.source-list: CheckBox {
            text: source.name;
            checked: source.checked;
            toggled => {
                source.checked = !source.checked;
            }
        }
        
        Button {
            height: 30px;
            width: 200px;
            text: "Apply Selected Sources";
            clicked => {
                root.apply-builds();
            }
        }
    }
}
