import { Button, VerticalBox, ListView, CheckBox } from "std-widgets.slint";

export struct UISource {
    label: string,
    value: string,
    checked: bool,
    is_aram: bool,
    is_urf: bool,
}

export component AppWindow inherits Window {
    in-out property<int> counter: 0;
    in-out property <[string]> selected;
    in-out property <[UISource]> sources;
    
    callback request-increase-value();
    callback updateChecked(string, bool);

    VerticalBox {
        Text {
            text: "计数: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }

    list-view := ListView {
        for item in root.sources:  HorizontalLayout {
            CheckBox {
                text: item.value;
                checked: item.checked;
                toggled => {
                    item.checked = self.checked;
                    root.updateChecked(item.value, self.checked);
                }
            }
        }
    }
}
