export struct UISource {
    label: string,
    value: string,
    checked: bool,
    is_aram: bool,
    is_urf: bool,
}

export struct UIRune {
    id: string,
    data: image,
}

export global GlobalSettings  {
    in property<bool> widgets-enabled: true;
    in-out property <[string]> selected;
    in-out property <[UISource]> sources;
    in property <string> auth_url;
    in property <bool> is_tencent;
    in property <[UIRune]> runes;

    callback update-selected-source(string, bool);
}
