import { Button, VerticalBox, ListView, CheckBox , HorizontalBox} from "std-widgets.slint";

export struct UISource {
    label: string,
    value: string,
    checked: bool,
    is_aram: bool,
    is_urf: bool,
}

export struct UIRune {
    id: string,
    data: image,
}

export component AppWindow inherits Window {
    min-width: 600px;
    min-height: 500px;

    in-out property <[string]> selected;
    in-out property <[UISource]> sources;
    in property <string> auth_url;
    in property <bool> is_tencent;
    in property <[UIRune]> runes;
    
    callback request-increase-value();
    callback update-selected-source(string, bool);

    VerticalLayout {
        HorizontalLayout {
            padding: 8px;

            Text {
                text: "ChampR";
                font-size: 42px;
                font-weight: 700;
                horizontal-alignment: center;
            }
        }
        HorizontalBox { 
            padding-left: 28px;

            Text {
                text: "Sources";
                font-size: 18px;
                font-weight: 500;
            }
        }
        list-view := ListView {
            padding-right: 24px;

            for item in root.sources: HorizontalLayout {
                padding-left: 24px;

                CheckBox {
                    text: item.label;
                    checked: item.checked;
                    toggled => {
                        item.checked = self.checked;
                        root.update-selected-source(item.value, self.checked);
                    }
                }
            }
        }
        HorizontalLayout {
            rune-list := ListView {
                for item in root.runes: HorizontalLayout {
                    Image {
                        source: item.data;
                    }
                }
            }
        }
        Text {
            text: root.auth_url;
            padding-left: 12px;
        }
    }
}
