import { Button, VerticalBox, ListView, CheckBox } from "std-widgets.slint";

export struct UISource {
    label: string,
    value: string,
    checked: bool,
    is_aram: bool,
    is_urf: bool,
}

export component AppWindow inherits Window {
    min-width: 600px;
    min-height: 500px;

    in-out property <[string]> selected;
    in-out property <[UISource]> sources;
    in-out property <string> auth_url;
    
    callback request-increase-value();
    callback update-selected-source(string, bool);

    VerticalLayout {
        HorizontalLayout {
            padding: 8px;

            Text {
                text: "ChampR";
                font-size: 42px;
                font-weight: 700;
                horizontal-alignment: center;
            }
        }
        Text {
            text: "Sources";
            font-size: 18px;
            font-weight: 500;
            padding-left: 12px;
        }
        list-view := ListView {
            padding: 8px;

            for item in root.sources:  HorizontalLayout {
                CheckBox {
                    text: item.label;
                    checked: item.checked;
                    toggled => {
                        item.checked = self.checked;
                        root.update-selected-source(item.value, self.checked);
                    }
                }
            }
        }
    }
}
