import { Button, VerticalBox, ListView, CheckBox , HorizontalBox} from "std-widgets.slint";

import { SideBar } from "./sidebar.slint";

import { SourceListPage, AboutPage, GlobalSettings } from "./pages/index.slint";
// import { GlobalSettings } from "./global_settings.slint";

export { GlobalSettings }

export component AppWindow inherits Window {
    title: "ChampR";
    icon: @image-url("../assets/icon@2x_r.png");
    preferred-width: 700px;
    preferred-height: 500px;

    callback request-increase-value();

    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("ChampR");
            model: [@tr("Menu" => "Sources"), @tr("Menu" => "About")];
        }

        if(side-bar.current-item == 0) : SourceListPage {}
        if(side-bar.current-item == 1) : AboutPage {}
    }

    // VerticalLayout {
    //     HorizontalLayout {
    //         padding: 8px;

    //         Text {
    //             text: "ChampR";
    //             font-size: 42px;
    //             font-weight: 700;
    //             horizontal-alignment: center;
    //         }
    //     }
    //     HorizontalBox {
    //         padding-left: 28px;

    //         Text {
    //             text: "Sources";
    //             font-size: 18px;
    //             font-weight: 500;
    //         }
    //     }
    //     list-view := ListView {
    //         padding-right: 24px;

    //         for item in root.sources: HorizontalLayout {
    //             padding-left: 24px;

    //             CheckBox {
    //                 text: item.label;
    //                 checked: item.checked;
    //                 toggled => {
    //                     item.checked = self.checked;
    //                     root.update-selected-source(item.value, self.checked);
    //                 }
    //             }
    //         }
    //     }
    //     HorizontalLayout {
    //         rune-list := ListView {
    //             for item in root.runes: HorizontalLayout {
    //                 Image {
    //                     source: item.data;
    //                 }
    //             }
    //         }
    //     }
    //     Text {
    //         text: root.auth_url;
    //         padding-left: 12px;
    //     }
    // }
}

// export component ChildWin inherits Window {
//     preferred-width: 500px;
//     preferred-height: 400px;
//     always-on-top: true;
//     title: @tr("Child window");

//     HorizontalLayout {
//         padding: 8px;

//         Text {
//             text: "Child window";
//             font-size: 42px;
//             font-weight: 700;
//             horizontal-alignment: center;
//         }
//     }
// }
